logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure: error
mybatis-plus:
    configuration:
        call-setters-on-nulls: true
    mapper-locations: classpath*:/mapper/**/*.xml
spring:
    datasource:
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/kssy_db_new?useUnicode=true&characterEncoding=UTF-8
        username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        auto-commit: true
        connection-timeout: 60000
        idle-timeout: 60000
        max-lifetime: 0
        maximum-pool-size: 5
        minimum-idle: 3
    main:
        allow-bean-definition-overriding: true
    redis:
        host: 192.168.153.139
        password: 123456
        port: 6379
server:
    max-http-header-size: 102400